### ISSUE TITLE
Testing Qoala-T model-based on old subjects with Alzheimer's disease

### ISSUE THREAD

**Issue by mattvan83** [Qoala-T/QC#13]
Dear Eduard,

First, thank you for this very useful tool regarding time-consuming process on Freesurfer preprocessed data. I was astonished by the speed of the predictions which is very fast !

I used the model-based script to determine the quality of two-hundred patients including healthy controls, mild cognitive impairment and alzheimer's disease patients. Do you think the model you built is appropriate regarding the old age of the majority of my patients ?

I was wondering if manually QC a subset of my patients would be benefit, but after having red the paper and taking into account the relatively small size of my sample I prefered use the model-based script.

I got two files in my output folder: one is .csv with results of prediction which seems well adressed, but I cannot open the second file "Figure_Rating_model_based_yourdataset.pdf" which seems to have no page... Do you have an idea on this problem ?

Finally, if I follow the troubleshooting of Freesurfer for manual editing patients below 70%, could I then relaunch the Qoala-T prediction on corrected patients to see if predictions have been improved ?

Best,
Matthieu

**Comment by eduardklap** [comment]
> First, thank you for this very useful tool regarding time-consuming process on Freesurfer preprocessed data. I was astonished by the speed of the predictions which is very fast !

Thanks! Good to hear that our tool is useful.

> Do you think the model you built is appropriate regarding the old age of the majority of my patients ?

It's hard to say for sure, since we did not test the model with older patients yet. However, the surface holes and white matter hypointensities are the most predictive for scan quality, so I think in older patients these features will relate similarly to scan quality as in the adolescent sample on which the model is based.

> I cannot open the second file "Figure_Rating_model_based_yourdataset.pdf" which seems to have no page... Do you have an idea on this problem ?

Not sure what is going on here. Did you get any output with `print(p)` (line 122)? Alternatively, you can use the Shiny app that provides the figure with predictions

> Finally, if I follow the troubleshooting of Freesurfer for manual editing patients below 70%, could I then relaunch the Qoala-T prediction on corrected patients to see if predictions have been improved ?

Great question, this is an open issue for now since we did not test the effects of editing. We hope that if editing has improved scan quality, this will show up in the Qoala-T ratings. If you are planning to do this, we would be very much interested in the results. Let us know if we can be of any help.

Best, Eduard
