### ISSUE TITLE
FreeSurfer high-resolution data

### ISSUE THREAD

**Issue by jhuguetn** [Qoala-T/QC#25]
Hi there,

I have a high-resolution sub-millimeter resolution dataset (n=360) processed both with FreeSurfer at [native resolution](https://surfer.nmr.mgh.harvard.edu/fswiki/SubmillimeterRecon) and at 1mm3 resolution (baseline `recon-all` command). 

Trying to automatically assess its quality, I've run QOALA-T to get some QC scores using the existing Braintime model. Generally speaking, scores I am getting are worse than I would initially expect for such high-resolution dataset (mean score below 50).  
In addition, and contrary to what i would initially expect, results from 1mm3 resampled data performed better overall than the FreeSurfer results at native resolution based on QOALA scores. 

How would you explain that? Do you recommend here building my own model instead of using the Braintime one?

Many thanks,
Jordi

**Comment by larawierenga** [comment]
Hi Jordi,

Thanks for using Qoala-T, that sounds like a fantastic dataset. We have not worked with such high resolution dataset before. Therefore I don’t know exactly how different they are from our resolution. What i guess might happen is that the number of surface holes (most predictive of quality) may differ between high and low resolution data. This may have contributed to the Qoala-T scores you mention. Have you visually inspected your data yet? And does it look overall good? I would recommend to use the manual QC protocol in the supplement on a subset of your data. If this is indeed very different then the Qoala-T score you could use this subset to build your model. If your visual scores are indeed very different from the Qoala-T scores you could use this subset to build your model. It might help to have the same resolution in the training and test set.

Hope this is helpful!

Lara and Eduard


On 18 Dec 2019, at 17:45, Jordi Huguet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I have a high-resolution sub-millimeter resolution dataset (n=360) processed both with FreeSurfer at native resolution<https://surfer.nmr.mgh.harvard.edu/fswiki/SubmillimeterRecon> and at 1mm3 resolution (baseline recon-all command).

Trying to automatically assess its quality, I've run QOALA-T to get some QC scores using the existing Braintime model. Generally speaking, scores I am getting are worse than I would initially expect for such high-resolution dataset (mean score below 50).
In addition, and contrary to what i would initially expect, results from 1mm3 resampled data performed better overall than the FreeSurfer results at native resolution based on QOALA scores.

How would you explain that? Do you recommend here building my own model instead of using the Braintime one?

Many thanks,
Jordi

**Comment by jhuguetn** [comment]
Hi Lara, 

I also believe that the number of surface holes affects the quality scoring and -indeed- FreeSurfer results of native high-resolution data have more surface holes than FreeSurfer results of data down-sampled at 1mm3. 

I guess building a model using our own data would be the way to go. 

Many thanks,
Jordi

**Comment by larawierenga** [comment]
Hi Jordi,

Sounds good, if you have any further questions please don’t hesitate to contact us.

Lara


On 8 Jan 2020, at 18:21, Jordi Huguet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lara,

I also believe that the number of surface holes affects the quality scoring and -indeed- FreeSurfer results of native high-resolution data have more surface holes than FreeSurfer results of data down-sampled at 1mm3.

I guess building a model using our own data would be the way to go.

Many thanks,
Jordi
