### ISSUE TITLE
Freesurfer v5.3?

### ISSUE THREAD

**Issue by rskl92** [Qoala-T/QC#26]
Hi,

I am new to using brain imaging data. I have access to a cohort but it seems that they used Freesurfer version 5.3. Is there any way I can use Qoala-T with this version? I know you mention that it is compatible with the newest version but I just wanted to confirm that a change in the code can't fix that before thinking about rerunning the raw images using the newer version?

Thanks

**Comment by larawierenga** [comment]
Hi Roxanna,

We have edited the stats2table R scripts to make it compatible with FreeSurfer 5.3. You would next need to use one of the R scripts to run the model rather than the shiny app (can be found here https://github.com/Qoala-T/QC/tree/master/Scripts/Qoala-T_Scripts). Yet since the model was trained on FS6.0 we highlight recommend to rerun your data in FS6.0.

Best regards,
Lara



On 3 Feb 2020, at 01:20, Roxanna KL <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am new to using brain imaging data. I have access to a cohort but it seems that they used Freesurfer version 5.3. Is there any way I can use Qoala-T with this version? I know you mention that it is compatible with the newest version but I just wanted to confirm that a change in the code can't fix that before thinking about rerunning the raw images using the newer version?

Thanks

**Comment by rskl92** [comment]
Hi Lara,

Thanks for your prompt response. Yes, makes a lot of sense to use Freesurfer v6.0 given the training data.
