### ISSUE TITLE
Error when I run A_model_based script

### ISSUE THREAD

**Issue by yosoy96jose** [Qoala-T/QC#27]
Hi, 
I am trying to use Qoala Tool for the first time (A_model_based script), but when I run the program this error appears:

> dataset_colnames <- names(rf.tune$trainingData)[-ncol(rf.tune$trainingData)]
> testing <- test_data[,dataset_colnames]
Error in `[.data.frame`(test_data, , dataset_colnames) : 
  undefined columns selected
> testing <- testing[complete.cases(testing),]
Error: object 'testing' not found

I think that the reason is that in the csv generated by stats2table script is missing this columns: BrainSegVol.to.eT1V, MaskVol.to.et1V, estimatedtotalintracranialVol

Any recommendations?, thanks

**Comment by larawierenga** [comment]
Hi,

Have you tried the shiny app instead? And not sure if you used the R script or bash script to generate your dataset, but you could also see wether the other one works well.

Let us know if this helped.

Lara

On 21 Feb 2020, at 22:31, yosoy96jose <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I am trying to use Qoala Tool for the first time (A_model_based script), but when I run the program this error appears:

dataset_colnames <- names(rf.tune$trainingData)[-ncol(rf.tune$trainingData)]
testing <- test_data[,dataset_colnames]
Error in [.data.frame(test_data, , dataset_colnames) :
undefined columns selected
testing <- testing[complete.cases(testing),]
Error: object 'testing' not found

I think that the reason is that in the csv generated by stats2table script is missing this columns: BrainSegVol.to.eT1V, MaskVol.to.et1V, estimatedtotalintracranialVol

Any recommendations?, thanks

**Comment by enjoy-our-life** [comment]
> Hi, I am trying to use Qoala Tool for the first time (A_model_based script), but when I run the program this error appears:
> 
> > dataset_colnames <- names(rf.tune$trainingData)[-ncol(rf.tune$trainingData)]
> > testing <- test_data[,dataset_colnames]
> > Error in `[.data.frame`(test_data, , dataset_colnames) :
> > undefined columns selected
> > testing <- testing[complete.cases(testing),]
> > Error: object 'testing' not found
> 
> I think that the reason is that in the csv generated by stats2table script is missing this columns: BrainSegVol.to.eT1V, MaskVol.to.et1V, estimatedtotalintracranialVol
> 
> Any recommendations?, thanks

Hi，how do you solve this problem?
