### ISSUE TITLE
Error when running Stats2Table.R with longitudinal freesurfer data

### ISSUE THREAD

**Issue by cschifani** [Qoala-T/QC#29]
Hi,

I tried running the Stats2Table.R script using freesurfer data generated with the longitudinal pipeline. Unfortunately, I am getting the following error:

Error in match.names(clabs, names(xi)) : 
  names do not match previous names 

I also tried running the script with normal freesurfer outputs which worked fine. So it seems that the script has a problem with the longitudinal outputs. 

Can you help me to get it to work in order to go on with the Qoala_T_A_model_based_github.R script?

Thanks,
Christin

Update since yesterday:
Since the R script was not working with my longitudinal freesurfer outputs, I tried using the stats2table_bash_qoala_t.sh script. The script ran fine and generated all files but when I uploaded those files to the QoalaT app and hit execute, I got an error. Again, when using normal freesurfer outputs instead of the longitudinal, it worked fine. What could be the problem with the longitudinal freesurfer outputs? The format of the stats and thickness/area files produced by stats2table_bash_qoala_t.sh look the same. Thanks!

**Comment by larawierenga** [comment]
Hi Christin,

The Qoala-T model is indeed based on the first step of the processing pipeline, the cross-sectional part. The longitudinal pipeline doesnt provide the number of surface holes, which we need for prediction. In our protocol we run the Qoala-T tool before the longitudinal pipeline, as scans with poor quality will affect the subject based template and herewith the scans of the other time points.

I hope this was helpful.

Best regards,
Lara

On 28 Apr 2020, at 17:53, cschifani <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

I tried running the Stats2Table.R script using freesurfer data generated with the longitudinal pipeline. Unfortunately, I am getting the following error:

Error in match.names(clabs, names(xi)) :
names do not match previous names

I also tried running the script with normal freesurfer outputs which worked fine. So it seems that the script has a problem with the longitudinal outputs.

Can you help me to get it to work in order to go on with the Qoala_T_A_model_based_github.R script?

Thanks,
Christin

**Comment by eduardklap** [comment]
To do: update readme with info on Qoala-T in longitudinal workflow
